include:
  - .gitlab/ci/*.gitlab-ci.yml

stages:
  - build
  - deploy
  - rollback

build-prod:
  stage: build
  extends: .build_template
  variables:
    ENV_TAG: latest
    DOCKERFILE: Dockerfile-prod
  only:
    - main

deploy-prod:
  stage: deploy
  extends: .deploy_template
  variables:
    NAMESPACE: qwatt-prod
    VALUES_FILE: .helm/values-prod.yml
    K8SCONFIGJSON: $UCODE_HZN_KUBECONFIG
  only:
    - main

rollback-prod:
  stage: rollback
  extends: .rollback_template
  variables:
    NAMESPACE: qwatt-prod
    K8SCONFIGJSON: $UCODE_HZN_KUBECONFIG
  when: manual
