FROM node:16.15.1 as builder
RUN apt update && apt-get install -y yarn

RUN mkdir app
WORKDIR app

COPY package*.json ./
COPY . ./

RUN npm i --legacy-peer-deps

RUN npm run build
ENTRYPOINT ["npm", "start"]

